VERSION="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GC6EZ4YTT3I2GYCLUFIJMKO534WAP2QOQUTMLFZ25CQRSIHA5S5QQL2Y"
]

[DOCUMENTATION]
ORG_NAME="Vexonic LLC"
ORG_URL="https://vexelcoin.com"
ORG_DESCRIPTION="Vexonic Team is made up of 10 software engeneeries that have a deep knowledge in the field of crypto and MetaVerse games. Our staff can help you at any time with any problems you encounter"
ORG_LOGO="https://vexelcoin.com/vagexchange.png"


[[CURRENCIES]]
code="VEXEL"
issuer="GC6EZ4YTT3I2GYCLUFIJMKO534WAP2QOQUTMLFZ25CQRSIHA5S5QQL2Y"
anchor_asset_type="crypto"
anchor_asset="VEXEL"
name="Vexel"
desc="VEXEL is the coin of vexonic which will allow you to purchase Vexilus ships to make money by playing Vexonic - a spaceshooter game only 30,000,000 VEXEL coins will exist"
image="https://vexelcoin.com/vagexchange.png"
fixed_number=300000000
max_number=300000000
is_unlimited=false
#VEXEL was issued using the open and inclusive Stellar blockchain network.


