VERSION="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GC6EZ4YTT3I2GYCLUFIJMKO534WAP2QOQUTMLFZ25CQRSIHA5S5QQL2Y"
]

[DOCUMENTATION]
ORG_NAME="Vexonic LLC"
ORG_URL="https://vexelcoin.com"
ORG_DESCRIPTION="Vexonic Team is made up of 10 software engeneeries that have a deep knowledge in the field of crypto and MetaVerse games. Our staff can help you at any time with any problems you encounter"
ORG_LOGO="https://vexelcoin.com/vexelicon.png"

[[PRINCIPALS]]
name="John Frank"
email="vexonicteam@gmail.com"
telegram="https://t.me/+OJZ3WdqM8FVkNDEy"

[[CURRENCIES]]
code="VEXEL"
issuer="GC6EZ4YTT3I2GYCLUFIJMKO534WAP2QOQUTMLFZ25CQRSIHA5S5QQL2Y"
anchor_asset_type="crypto"
anchor_asset="VEXEL"
name="Vexel"
desc="Vexel coin is the main currency of the Vexonic game. Having this coin, you will be able to participate in pools, purchase ships, nft, participate in giveaways and many other possibilities. More info you can get at our web"
conditions = "There will only ever be 30,000,000 VEXEL in existence."
image="https://vexelcoin.com/vexelicon.png"
fixed_number=300000000
max_number=300000000
is_unlimited=false
#VEXEL was issued using the open and inclusive Stellar blockchain network.


