VERSION="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GAXZ3RSP6X53LD5IRGYNPUZEE6W6M3LDEXEUIGSKTBJATEXEZINKHDWD","GC6EZ4YTT3I2GYCLUFIJMKO534WAP2QOQUTMLFZ25CQRSIHA5S5QQL2Y"
]


[DOCUMENTATION]
ORG_NAME="Vexonic LLC"
URL="https://vexelcoin.com"

[[PRINCIPALS]]
name="Andrew Jester"
email="vexelcoin@gmail.com"
telegram="https://t.me/+OJZ3WdqM8FVkNDEy"

[[CURRENCIES]]
code="VEXEL"
issuer = "GC6EZ4YTT3I2GYCLUFIJMKO534WAP2QOQUTMLFZ25CQRSIHA5S5QQL2Y"
name = "VEXEL"
desc = "VEXEL is the coin of vexonic which will allow you to purchase Vexilus ships to make money by playing Vexonic- a spaceshooter game"
conditions = "There will only ever be 30,000,000 VEXEL in existence."
image = "https://i.ibb.co/q5BSqJD/IMG-4649.jpg"



